# Generated by Django 3.1.6 on 2021-08-08 10:47

import ckeditor_uploader.fields
import config.views
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Заголовок')),
                ('slug', models.CharField(help_text='Заполняется автоматически', max_length=130, verbose_name='URL адрес')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст публикации')),
                ('image', models.ImageField(blank=True, upload_to=config.views.get_upload_to, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Заголовок')),
                ('slug', models.CharField(help_text='Заполняется автоматически', max_length=130, verbose_name='URL адрес')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('show_main', models.BooleanField(default=False, verbose_name='Отображать на главной?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=130, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to=config.views.get_upload_to, verbose_name='Изображение')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.article', verbose_name='Статья')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='section.section', verbose_name='Раздел'),
        ),
    ]
