# Generated by Django 3.1.6 on 2021-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=130, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(blank=True, verbose_name='Значение'),
        ),
    ]
