# Generated by Django 3.1.6 on 2021-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210815_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(blank=True, max_length=210, verbose_name='Значение'),
        ),
    ]
